apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextjs-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextjs-demo
  template:
    metadata:
      labels:
        app: nextjs-demo
    spec:
      containers:
      - name: nextjs-demo
        image: nextjs-demo:latest
        ports:
        - containerPort: 3000

